name: flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  # Androidのビルドジョブ
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
      # https://github.com/subosito/flutter-action
      - name: CIジョブを動かすためのflutterの環境構築
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - name: CIジョブを動かすためのJavaの環境構築
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 正常にインストールできているかを確認
        run: flutter --version
      - name: パッケージのインストール
        run: flutter pub get
      - name: Androidの成果物をビルド
        run: |  
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore   
          export KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}"
          export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
          export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
          flutter build apk
      - run: flutter build appbundle


  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.7.7'
  #         channel: 'stable'
  #     - run: flutter pub get
  #     - run: flutter build ios --release --no-codesign

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: チェックアウト
  #       uses: actions/checkout@v3
  #     # https://github.com/subosito/flutter-action
  #     - name: CIジョブを動かすためのflutterの環境構築
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.7.7'
  #         channel: 'stable'
  #     - name: 正常にインストールできているかを確認
  #       run: flutter --version
  #     - name: パッケージのインストール
  #       run: flutter pub get
  #     - name: テストを実行
  #       run: flutter test 
